@GHLearning.EasyMassTransitRabbitMQ.RequestResponseClient_HostAddress = http://localhost:5046

GET {{GHLearning.EasyMassTransitRabbitMQ.RequestResponseClient_HostAddress}}/weatherforecast/
Accept: application/json

###
