@GHLearning.EasyMassTransitRabbitMQ.FanoutClient_HostAddress = http://localhost:5192

GET {{GHLearning.EasyMassTransitRabbitMQ.FanoutClient_HostAddress}}/weatherforecast/
Accept: application/json

###
