@GHLearning.EasyMassTransitRabbitMQ.DirectServer_HostAddress = http://localhost:5261

GET {{GHLearning.EasyMassTransitRabbitMQ.DirectServer_HostAddress}}/weatherforecast/
Accept: application/json

###
