@GHLearning.EasyMassTransitRabbitMQ.RequestResponseServer_HostAddress = http://localhost:5267

GET {{GHLearning.EasyMassTransitRabbitMQ.RequestResponseServer_HostAddress}}/weatherforecast/
Accept: application/json

###
